import clsx from 'clsx'
import '../globals.css'
import { Montserrat } from 'next/font/google'
import { Providers } from '@/components/Providers'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx(montserrat.variable, montserrat.className, 'dark:bg-chambray-950')}>
      <body className="max-w-5xl mx-auto py-2">{children}</body>
    </html>
  )
}
