import clsx from 'clsx'
import '../globals.css'
import { Inter, Montserrat } from 'next/font/google'
import Providers from '@/components/Providers'
import { ServerThemeProvider } from 'next-themes'
import Navbar from '@/components/Navbar'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ServerThemeProvider attribute="class">
      <html suppressHydrationWarning lang="en" className={clsx(montserrat.variable, montserrat.className, inter.variable, inter.className,)}>
        <body className="max-w-5xl mx-auto py-2 dark:bg-chambray-950">
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </html>
    </ServerThemeProvider>
  )
}
