import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body  className="max-w-5xl mx-auto py-2">{children}</body>
    </html>
  )
}
